version: '3.7'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 --workers 2 dashboard.wsgi
    volumes:
      - .:/usr/src/app/
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
    
  web_instance_2:
    build: .
    command: gunicorn --bind 0.0.0.0:8001 --workers 2 dashboard.wsgi
    volumes:
      - .:/usr/src/app/
    expose:
      - 8001
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
volumes:
  postgres_data: